<<<<<<< HEAD:accounts/migrations/0002_auto_20191127_2144.py
# Generated by Django 2.2.7 on 2019-11-27 12:44
=======
# Generated by Django 2.2.7 on 2019-11-27 12:42
>>>>>>> c32f8fda99493b4a15bf13957d963fdb8489ddff:accounts/migrations/0002_auto_20191127_2142.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:accounts/migrations/0002_auto_20191127_2144.py
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
=======
        ('auth', '0011_update_proxy_permissions'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
>>>>>>> c32f8fda99493b4a15bf13957d963fdb8489ddff:accounts/migrations/0002_auto_20191127_2142.py
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
