<<<<<<< HEAD:accounts/migrations/0002_auto_20191128_0318.py
# Generated by Django 2.2.7 on 2019-11-27 18:18
=======
# Generated by Django 2.2.7 on 2019-11-27 18:38
>>>>>>> 95c3f5554ba6b072f9e3bd13382445b43bb514c9:accounts/migrations/0002_auto_20191128_0338.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
