# Generated by Django 2.2.7 on 2019-11-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191127_2142'),
        ('accounts', '0002_auto_20191127_2144'),
    ]

    operations = [
    ]
