# Generated by Django 2.2.7 on 2019-11-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191127_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
