# Generated by Django 2.2.7 on 2019-11-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191125_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genreId',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieId',
        ),
    ]
